### PR TITLE
Dashboard - Update xel and partially fix electron api

### LINKED ISSUE #102: Dashboard loads empty page
running the ui via `npm start`

results in an empty page
image

enabling javascript debugger shows an error
```
Uncaught ReferenceError: ClientRect is not defined
    at xel.min.html:1
    at xel.min.html:1
```

seems `ClientRect` was replace with `DOMRect` https://bugs.chromium.org/p/chromium/issues/detail?id=719246

this should be resolved in a newer version of `xel`

### PR DESCRIPTION
**Pull request by kumavis**
tried to take the dashboard for a spin but it seems broken

took some steps to fix it but ultimately don't know what its supposed to do or what sort of file its supposed to be able to import

Fixes #102

### CODE REVIEW

**Comment by kumavis** [comment]
what type of file should i be able to load? the jalangi json? `la ../tests/numbers/infoflow_jalangi_.json`

**Comment by kumavis** [comment]
The current state of the PR is that it now correctly loads the ui, however the `Analyze` and `Load` buttons are still broken, as I don't know what kind of data they are supposed to consume

image

**Comment by jawline** [comment]
Analyze takes a js file, and load takes the output from save (essentially this is a log of analysis, I'm not sure if it will still work though). 

The UI component of the tool hasn't been looked at in a long time, I built it because I thought the coverage graph generation would be more useful but haven't notably used it since 2018 so it's bound to be super out of date

**Comment by kumavis** [comment]
@jawline seems to work now

**Comment by jawline** [comment]
Oh wow this is a lot of work, thanks for putting the time in.

**Pull request merged**
